# Generated by Django 4.2.4 on 2023-09-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('CLI', 'Cliente'), ('FUN', 'Funcionário')], default='CLI', max_length=50),
        ),
    ]
