# Generated by Django 4.2.3 on 2023-08-14 21:17

import core.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(error_messages={'null': 'Campo obrigatório'}, max_length=255, validators=[core.validator.validar_campo_vazio]),
        ),
    ]
