# Generated by Django 4.2.4 on 2023-09-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('cod_barras', models.IntegerField(max_length=13)),
                ('preco_produto', models.IntegerField(max_length=10)),
                ('qtd_produto', models.IntegerField(max_length=10)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
