# Generated by Django 4.2.4 on 2023-10-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod_barras',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_produto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd_produto',
            field=models.IntegerField(),
        ),
    ]
